//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimarket_Raphi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoja_de_Registro
    {
        public string ID_HojaRegistro { get; set; }
        public Nullable<int> Saldo_Final_Mensual { get; set; }
        public string Codigo_Empleado { get; set; }
        public string Area { get; set; }
        public string Turno { get; set; }
        public int Dia { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
        public string ID_Kardex { get; set; }
    
        public virtual Kardex Kardex { get; set; }
    }
}
