//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimarket_Raphi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex_SV
    {
        public string ID_Kardex { get; set; }
        public int Salida_Venta { get; set; }
    }
}
