//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minimarket_Raphi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kardex()
        {
            this.Hoja_de_Registro = new HashSet<Hoja_de_Registro>();
        }
    
        public string ID_Kardex { get; set; }
        public decimal Saldo_Inicial { get; set; }
        public Nullable<decimal> Saldo_Final { get; set; }
        public decimal Monto_Venta { get; set; }
        public string Codigo_Empleado { get; set; }
        public Nullable<decimal> Ganancia { get; set; }
        public int Dia { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoja_de_Registro> Hoja_de_Registro { get; set; }
    }
}
